version: '{build} {branch}'

image: [Ubuntu2204]

init:
  - appveyor version
  - sh: type lsb_release && lsb_release -a || true
  - sh: type uname && uname -a || true

services:
  - docker

install:
  - time docker pull ghcr.io/knossos-project/arch
build_script:
  - time docker run --privileged --cap-add=ALL -v /lib/modules:/lib/modules -v /dev:/dev -v ${APPVEYOR_BUILD_FOLDER}:/root/knossos ghcr.io/knossos-project/arch bash -c '/root/knossos/ci/build_linux_deps.sh'
artifacts: {path: '*.pkg.tar.zst'}

deploy:
  - provider: GitHub
    tag: nightly-dev
    auth_token:
      secure: t9BAyR+k93XD/dXN/gaOgApdGKOxb4lvDtpci8pHHxghvSxd/wNGdFFe/N9WqZSr
    artifact: /.*.pkg.tar.zst/
    prerelease: true
    force_update: true
