//static uint32_t setOGLforVP(uint32_t currentVP, struct stateInfo *state);
//static uint32_t overlayOrthogonalVpPixel(uint32_t currentVP, Coordinate position, color4F color, struct stateInfo *state);
static GLuint renderWholeSkeleton(struct stateInfo *state);
static GLuint renderSuperCubeSkeleton(struct stateInfo *state, Byte callFlag);
static GLuint renderActiveTreeSkeleton(struct stateInfo *state, Byte callFlag);
static uint32_t renderCylinder(int32_t coordinateMag, Coordinate *base, float baseRadius, Coordinate *top, float topRadius);
static uint32_t renderSphere(int32_t coordinateMag, Coordinate *pos, float radius);
static uint32_t renderText(int32_t coordinateMag, Coordinate *pos, char *string);
uint32_t updateDisplayListsSkeleton(struct stateInfo *state);
static uint32_t renderSegPlaneIntersection(struct segmentListElement *segment, struct stateInfo *state);
static uint32_t renderViewportBorders(uint32_t currentVP);
