# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'knossos_cuber_widgets.ui'
#
# Created: Thu Jan 15 17:58:54 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(500, 344)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_target_dir = QtGui.QLabel(self.tab)
        self.label_target_dir.setObjectName(_fromUtf8("label_target_dir"))
        self.gridLayout.addWidget(self.label_target_dir, 2, 0, 1, 1)
        self.push_button_choose_target_dir = QtGui.QPushButton(self.tab)
        self.push_button_choose_target_dir.setObjectName(_fromUtf8("push_button_choose_target_dir"))
        self.gridLayout.addWidget(self.push_button_choose_target_dir, 2, 1, 1, 1)
        self.push_button_choose_source_dir = QtGui.QPushButton(self.tab)
        self.push_button_choose_source_dir.setObjectName(_fromUtf8("push_button_choose_source_dir"))
        self.gridLayout.addWidget(self.push_button_choose_source_dir, 1, 1, 1, 1)
        self.label_experiment_name = QtGui.QLabel(self.tab)
        self.label_experiment_name.setObjectName(_fromUtf8("label_experiment_name"))
        self.gridLayout.addWidget(self.label_experiment_name, 0, 0, 1, 1)
        self.label_source_dir = QtGui.QLabel(self.tab)
        self.label_source_dir.setObjectName(_fromUtf8("label_source_dir"))
        self.gridLayout.addWidget(self.label_source_dir, 1, 0, 1, 1)
        self.line_edit_experiment_name = QtGui.QLineEdit(self.tab)
        self.line_edit_experiment_name.setObjectName(_fromUtf8("line_edit_experiment_name"))
        self.gridLayout.addWidget(self.line_edit_experiment_name, 0, 1, 1, 1)
        self.label_source_format = QtGui.QLabel(self.tab)
        self.label_source_format.setObjectName(_fromUtf8("label_source_format"))
        self.gridLayout.addWidget(self.label_source_format, 3, 0, 1, 1)
        self.combo_box_source_format = QtGui.QComboBox(self.tab)
        self.combo_box_source_format.setObjectName(_fromUtf8("combo_box_source_format"))
        self.gridLayout.addWidget(self.combo_box_source_format, 3, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.line_edit_scaling_z = QtGui.QLineEdit(self.tab_2)
        self.line_edit_scaling_z.setObjectName(_fromUtf8("line_edit_scaling_z"))
        self.gridLayout_2.addWidget(self.line_edit_scaling_z, 1, 6, 1, 1)
        self.label_boundaries_z = QtGui.QLabel(self.tab_2)
        self.label_boundaries_z.setObjectName(_fromUtf8("label_boundaries_z"))
        self.gridLayout_2.addWidget(self.label_boundaries_z, 2, 5, 1, 1)
        self.line_edit_boundaries_x = QtGui.QLineEdit(self.tab_2)
        self.line_edit_boundaries_x.setObjectName(_fromUtf8("line_edit_boundaries_x"))
        self.gridLayout_2.addWidget(self.line_edit_boundaries_x, 2, 2, 1, 1)
        self.label_source_datatype = QtGui.QLabel(self.tab_2)
        self.label_source_datatype.setObjectName(_fromUtf8("label_source_datatype"))
        self.gridLayout_2.addWidget(self.label_source_datatype, 0, 0, 1, 1)
        self.label_scaling_z = QtGui.QLabel(self.tab_2)
        self.label_scaling_z.setObjectName(_fromUtf8("label_scaling_z"))
        self.gridLayout_2.addWidget(self.label_scaling_z, 1, 5, 1, 1)
        self.label_scaling_x = QtGui.QLabel(self.tab_2)
        self.label_scaling_x.setObjectName(_fromUtf8("label_scaling_x"))
        self.gridLayout_2.addWidget(self.label_scaling_x, 1, 1, 1, 1)
        self.line_edit_scaling_x = QtGui.QLineEdit(self.tab_2)
        self.line_edit_scaling_x.setObjectName(_fromUtf8("line_edit_scaling_x"))
        self.gridLayout_2.addWidget(self.line_edit_scaling_x, 1, 2, 1, 1)
        self.label_boundaries = QtGui.QLabel(self.tab_2)
        self.label_boundaries.setObjectName(_fromUtf8("label_boundaries"))
        self.gridLayout_2.addWidget(self.label_boundaries, 2, 0, 1, 1)
        self.line_edit_scaling_y = QtGui.QLineEdit(self.tab_2)
        self.line_edit_scaling_y.setObjectName(_fromUtf8("line_edit_scaling_y"))
        self.gridLayout_2.addWidget(self.line_edit_scaling_y, 1, 4, 1, 1)
        self.line_edit_boundaries_z = QtGui.QLineEdit(self.tab_2)
        self.line_edit_boundaries_z.setObjectName(_fromUtf8("line_edit_boundaries_z"))
        self.gridLayout_2.addWidget(self.line_edit_boundaries_z, 2, 6, 1, 1)
        self.line_edit_boundaries_y = QtGui.QLineEdit(self.tab_2)
        self.line_edit_boundaries_y.setObjectName(_fromUtf8("line_edit_boundaries_y"))
        self.gridLayout_2.addWidget(self.line_edit_boundaries_y, 2, 4, 1, 1)
        self.label_scaling_y = QtGui.QLabel(self.tab_2)
        self.label_scaling_y.setObjectName(_fromUtf8("label_scaling_y"))
        self.gridLayout_2.addWidget(self.label_scaling_y, 1, 3, 1, 1)
        self.label_boundaries_y = QtGui.QLabel(self.tab_2)
        self.label_boundaries_y.setObjectName(_fromUtf8("label_boundaries_y"))
        self.gridLayout_2.addWidget(self.label_boundaries_y, 2, 3, 1, 1)
        self.label_scaling = QtGui.QLabel(self.tab_2)
        self.label_scaling.setObjectName(_fromUtf8("label_scaling"))
        self.gridLayout_2.addWidget(self.label_scaling, 1, 0, 1, 1)
        self.label_source_dimensions = QtGui.QLabel(self.tab_2)
        self.label_source_dimensions.setObjectName(_fromUtf8("label_source_dimensions"))
        self.gridLayout_2.addWidget(self.label_source_dimensions, 3, 0, 1, 1)
        self.line_edit_source_dimensions_x = QtGui.QLineEdit(self.tab_2)
        self.line_edit_source_dimensions_x.setObjectName(_fromUtf8("line_edit_source_dimensions_x"))
        self.gridLayout_2.addWidget(self.line_edit_source_dimensions_x, 3, 2, 1, 1)
        self.label_source_dimensions_y = QtGui.QLabel(self.tab_2)
        self.label_source_dimensions_y.setObjectName(_fromUtf8("label_source_dimensions_y"))
        self.gridLayout_2.addWidget(self.label_source_dimensions_y, 3, 3, 1, 1)
        self.line_edit_source_dimensions_y = QtGui.QLineEdit(self.tab_2)
        self.line_edit_source_dimensions_y.setObjectName(_fromUtf8("line_edit_source_dimensions_y"))
        self.gridLayout_2.addWidget(self.line_edit_source_dimensions_y, 3, 4, 1, 1)
        self.label_boundaries_x = QtGui.QLabel(self.tab_2)
        self.label_boundaries_x.setObjectName(_fromUtf8("label_boundaries_x"))
        self.gridLayout_2.addWidget(self.label_boundaries_x, 2, 1, 1, 1)
        self.label_source_dimensions_x = QtGui.QLabel(self.tab_2)
        self.label_source_dimensions_x.setObjectName(_fromUtf8("label_source_dimensions_x"))
        self.gridLayout_2.addWidget(self.label_source_dimensions_x, 3, 1, 1, 1)
        self.combo_box_source_datatype = QtGui.QComboBox(self.tab_2)
        self.combo_box_source_datatype.setObjectName(_fromUtf8("combo_box_source_datatype"))
        self.combo_box_source_datatype.addItem(_fromUtf8(""))
        self.combo_box_source_datatype.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.combo_box_source_datatype, 0, 1, 1, 6)
        self.check_box_swap_axes = QtGui.QCheckBox(self.tab_2)
        self.check_box_swap_axes.setEnabled(True)
        self.check_box_swap_axes.setChecked(True)
        self.check_box_swap_axes.setObjectName(_fromUtf8("check_box_swap_axes"))
        self.gridLayout_2.addWidget(self.check_box_swap_axes, 3, 5, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_downsampling_workers = QtGui.QLabel(self.tab_3)
        self.label_downsampling_workers.setObjectName(_fromUtf8("label_downsampling_workers"))
        self.gridLayout_3.addWidget(self.label_downsampling_workers, 4, 0, 1, 1)
        self.label_buffer_size_in_cubes = QtGui.QLabel(self.tab_3)
        self.label_buffer_size_in_cubes.setObjectName(_fromUtf8("label_buffer_size_in_cubes"))
        self.gridLayout_3.addWidget(self.label_buffer_size_in_cubes, 2, 0, 1, 1)
        self.spin_box_downsampling_workers = QtGui.QSpinBox(self.tab_3)
        self.spin_box_downsampling_workers.setMaximum(10000000)
        self.spin_box_downsampling_workers.setProperty("value", 10)
        self.spin_box_downsampling_workers.setObjectName(_fromUtf8("spin_box_downsampling_workers"))
        self.gridLayout_3.addWidget(self.spin_box_downsampling_workers, 4, 1, 1, 1)
        self.spin_box_compression_workers = QtGui.QSpinBox(self.tab_3)
        self.spin_box_compression_workers.setMaximum(1000000000)
        self.spin_box_compression_workers.setProperty("value", 20)
        self.spin_box_compression_workers.setObjectName(_fromUtf8("spin_box_compression_workers"))
        self.gridLayout_3.addWidget(self.spin_box_compression_workers, 5, 1, 1, 1)
        self.label_cube_edge_length = QtGui.QLabel(self.tab_3)
        self.label_cube_edge_length.setObjectName(_fromUtf8("label_cube_edge_length"))
        self.gridLayout_3.addWidget(self.label_cube_edge_length, 3, 0, 1, 1)
        self.spin_box_cube_edge_length = QtGui.QSpinBox(self.tab_3)
        self.spin_box_cube_edge_length.setMaximum(10000000)
        self.spin_box_cube_edge_length.setProperty("value", 128)
        self.spin_box_cube_edge_length.setObjectName(_fromUtf8("spin_box_cube_edge_length"))
        self.gridLayout_3.addWidget(self.spin_box_cube_edge_length, 3, 1, 1, 1)
        self.radio_button_start_from_mag1 = QtGui.QRadioButton(self.tab_3)
        self.radio_button_start_from_mag1.setChecked(False)
        self.radio_button_start_from_mag1.setObjectName(_fromUtf8("radio_button_start_from_mag1"))
        self.gridLayout_3.addWidget(self.radio_button_start_from_mag1, 0, 1, 1, 1)
        self.radio_button_start_from_2d_images = QtGui.QRadioButton(self.tab_3)
        self.radio_button_start_from_2d_images.setEnabled(True)
        self.radio_button_start_from_2d_images.setChecked(True)
        self.radio_button_start_from_2d_images.setObjectName(_fromUtf8("radio_button_start_from_2d_images"))
        self.gridLayout_3.addWidget(self.radio_button_start_from_2d_images, 0, 0, 1, 1)
        self.label_compression_workers = QtGui.QLabel(self.tab_3)
        self.label_compression_workers.setObjectName(_fromUtf8("label_compression_workers"))
        self.gridLayout_3.addWidget(self.label_compression_workers, 5, 0, 1, 1)
        self.check_box_downsample = QtGui.QCheckBox(self.tab_3)
        self.check_box_downsample.setChecked(True)
        self.check_box_downsample.setObjectName(_fromUtf8("check_box_downsample"))
        self.gridLayout_3.addWidget(self.check_box_downsample, 1, 0, 1, 1)
        self.check_box_skip_already_generated = QtGui.QCheckBox(self.tab_3)
        self.check_box_skip_already_generated.setChecked(True)
        self.check_box_skip_already_generated.setObjectName(_fromUtf8("check_box_skip_already_generated"))
        self.gridLayout_3.addWidget(self.check_box_skip_already_generated, 1, 1, 1, 1)
        self.spin_box_buffer_size_in_cubes = QtGui.QSpinBox(self.tab_3)
        self.spin_box_buffer_size_in_cubes.setMaximum(100000000)
        self.spin_box_buffer_size_in_cubes.setProperty("value", 1000)
        self.spin_box_buffer_size_in_cubes.setObjectName(_fromUtf8("spin_box_buffer_size_in_cubes"))
        self.gridLayout_3.addWidget(self.spin_box_buffer_size_in_cubes, 2, 1, 1, 1)
        self.label_io_workers = QtGui.QLabel(self.tab_3)
        self.label_io_workers.setObjectName(_fromUtf8("label_io_workers"))
        self.gridLayout_3.addWidget(self.label_io_workers, 6, 0, 1, 1)
        self.spin_box_io_workers = QtGui.QSpinBox(self.tab_3)
        self.spin_box_io_workers.setMaximum(100000000)
        self.spin_box_io_workers.setProperty("value", 20)
        self.spin_box_io_workers.setObjectName(_fromUtf8("spin_box_io_workers"))
        self.gridLayout_3.addWidget(self.spin_box_io_workers, 6, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_path_to_openjpeg = QtGui.QLabel(self.tab_4)
        self.label_path_to_openjpeg.setObjectName(_fromUtf8("label_path_to_openjpeg"))
        self.gridLayout_4.addWidget(self.label_path_to_openjpeg, 1, 0, 1, 1)
        self.line_edit_path_to_openjpeg = QtGui.QLineEdit(self.tab_4)
        self.line_edit_path_to_openjpeg.setObjectName(_fromUtf8("line_edit_path_to_openjpeg"))
        self.gridLayout_4.addWidget(self.line_edit_path_to_openjpeg, 1, 1, 1, 1)
        self.push_button_path_to_openjpeg = QtGui.QPushButton(self.tab_4)
        self.push_button_path_to_openjpeg.setObjectName(_fromUtf8("push_button_path_to_openjpeg"))
        self.gridLayout_4.addWidget(self.push_button_path_to_openjpeg, 1, 2, 1, 1)
        self.label_compression_quality = QtGui.QLabel(self.tab_4)
        self.label_compression_quality.setObjectName(_fromUtf8("label_compression_quality"))
        self.gridLayout_4.addWidget(self.label_compression_quality, 3, 0, 1, 1)
        self.label_compression_algorithm = QtGui.QLabel(self.tab_4)
        self.label_compression_algorithm.setObjectName(_fromUtf8("label_compression_algorithm"))
        self.gridLayout_4.addWidget(self.label_compression_algorithm, 2, 0, 1, 1)
        self.label_gauss_filter = QtGui.QLabel(self.tab_4)
        self.label_gauss_filter.setObjectName(_fromUtf8("label_gauss_filter"))
        self.gridLayout_4.addWidget(self.label_gauss_filter, 4, 0, 1, 1)
        self.combo_box_compression_algorithm = QtGui.QComboBox(self.tab_4)
        self.combo_box_compression_algorithm.setObjectName(_fromUtf8("combo_box_compression_algorithm"))
        self.combo_box_compression_algorithm.addItem(_fromUtf8(""))
        self.combo_box_compression_algorithm.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.combo_box_compression_algorithm, 2, 1, 1, 2)
        self.spin_box_compression_quality = QtGui.QSpinBox(self.tab_4)
        self.spin_box_compression_quality.setProperty("value", 70)
        self.spin_box_compression_quality.setObjectName(_fromUtf8("spin_box_compression_quality"))
        self.gridLayout_4.addWidget(self.spin_box_compression_quality, 3, 1, 1, 2)
        self.spin_box_double_gauss_filter = QtGui.QDoubleSpinBox(self.tab_4)
        self.spin_box_double_gauss_filter.setProperty("value", 0.5)
        self.spin_box_double_gauss_filter.setObjectName(_fromUtf8("spin_box_double_gauss_filter"))
        self.gridLayout_4.addWidget(self.spin_box_double_gauss_filter, 4, 1, 1, 2)
        self.check_box_compress = QtGui.QCheckBox(self.tab_4)
        self.check_box_compress.setChecked(True)
        self.check_box_compress.setObjectName(_fromUtf8("check_box_compress"))
        self.gridLayout_4.addWidget(self.check_box_compress, 0, 0, 1, 3)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.push_button_start_job = QtGui.QPushButton(Dialog)
        self.push_button_start_job.setObjectName(_fromUtf8("push_button_start_job"))
        self.horizontalLayout.addWidget(self.push_button_start_job)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.line_edit_experiment_name, self.push_button_choose_source_dir)
        Dialog.setTabOrder(self.push_button_choose_source_dir, self.push_button_choose_target_dir)
        Dialog.setTabOrder(self.push_button_choose_target_dir, self.combo_box_source_format)
        Dialog.setTabOrder(self.combo_box_source_format, self.push_button_start_job)
        Dialog.setTabOrder(self.push_button_start_job, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.combo_box_source_datatype)
        Dialog.setTabOrder(self.combo_box_source_datatype, self.line_edit_scaling_x)
        Dialog.setTabOrder(self.line_edit_scaling_x, self.line_edit_scaling_y)
        Dialog.setTabOrder(self.line_edit_scaling_y, self.line_edit_scaling_z)
        Dialog.setTabOrder(self.line_edit_scaling_z, self.line_edit_boundaries_x)
        Dialog.setTabOrder(self.line_edit_boundaries_x, self.line_edit_boundaries_y)
        Dialog.setTabOrder(self.line_edit_boundaries_y, self.line_edit_boundaries_z)
        Dialog.setTabOrder(self.line_edit_boundaries_z, self.line_edit_source_dimensions_x)
        Dialog.setTabOrder(self.line_edit_source_dimensions_x, self.line_edit_source_dimensions_y)
        Dialog.setTabOrder(self.line_edit_source_dimensions_y, self.check_box_swap_axes)
        Dialog.setTabOrder(self.check_box_swap_axes, self.line_edit_path_to_openjpeg)
        Dialog.setTabOrder(self.line_edit_path_to_openjpeg, self.push_button_path_to_openjpeg)
        Dialog.setTabOrder(self.push_button_path_to_openjpeg, self.combo_box_compression_algorithm)
        Dialog.setTabOrder(self.combo_box_compression_algorithm, self.spin_box_compression_quality)
        Dialog.setTabOrder(self.spin_box_compression_quality, self.spin_box_double_gauss_filter)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Knossos Cuber", None))
        self.label_target_dir.setToolTip(_translate("Dialog", "<html><head/><body><p>Where to write the output cubes.</p></body></html>", None))
        self.label_target_dir.setText(_translate("Dialog", "<no target dir>", None))
        self.push_button_choose_target_dir.setToolTip(_translate("Dialog", "<html><head/><body><p>Where to write the output cubes.</p></body></html>", None))
        self.push_button_choose_target_dir.setText(_translate("Dialog", "Choose Target Directory", None))
        self.push_button_choose_source_dir.setToolTip(_translate("Dialog", "<html><head/><body><p>Path to 2D images or full-resolution (mag1) cubes.</p></body></html>", None))
        self.push_button_choose_source_dir.setText(_translate("Dialog", "Choose Source Directory", None))
        self.label_experiment_name.setToolTip(_translate("Dialog", "<html><head/><body><p>Arbitrary experiment name identifier</p></body></html>", None))
        self.label_experiment_name.setText(_translate("Dialog", "Experiment Name", None))
        self.label_source_dir.setToolTip(_translate("Dialog", "<html><head/><body><p>Path to 2D images or full-resolution (mag1) cubes.</p></body></html>", None))
        self.label_source_dir.setText(_translate("Dialog", "<no source dir>", None))
        self.line_edit_experiment_name.setToolTip(_translate("Dialog", "<html><head/><body><p>Arbitrary experiment name identifier.</p></body></html>", None))
        self.line_edit_experiment_name.setText(_translate("Dialog", "test_stack", None))
        self.label_source_format.setToolTip(_translate("Dialog", "<html><head/><body><p>Whatever image format PIL can read in, or \'raw\' for faster cubing. Must be identical to the file name extension of input data.</p></body></html>", None))
        self.label_source_format.setText(_translate("Dialog", "Source Format", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "General", None))
        self.line_edit_scaling_z.setToolTip(_translate("Dialog", "<html><head/><body><p>Voxel scaling, physical units per voxel.</p></body></html>", None))
        self.line_edit_scaling_z.setText(_translate("Dialog", "1.0", None))
        self.label_boundaries_z.setToolTip(_translate("Dialog", "<html><head/><body><p>Edge length of whole dataset, only required if not starting from 2D images.</p></body></html>", None))
        self.label_boundaries_z.setText(_translate("Dialog", "z", None))
        self.line_edit_boundaries_x.setToolTip(_translate("Dialog", "<html><head/><body><p>Edge length of whole dataset, only required if not starting from 2D images.</p></body></html>", None))
        self.label_source_datatype.setToolTip(_translate("Dialog", "<html><head/><body><p>Input image pixel data type, required only for raw.</p></body></html>", None))
        self.label_source_datatype.setText(_translate("Dialog", "Source Datatype", None))
        self.label_scaling_z.setToolTip(_translate("Dialog", "<html><head/><body><p>Voxel scaling, physical units per voxel.</p></body></html>", None))
        self.label_scaling_z.setText(_translate("Dialog", "z", None))
        self.label_scaling_x.setToolTip(_translate("Dialog", "<html><head/><body><p>Voxel scaling, physical units per voxel.</p></body></html>", None))
        self.label_scaling_x.setText(_translate("Dialog", "x", None))
        self.line_edit_scaling_x.setToolTip(_translate("Dialog", "<html><head/><body><p>Voxel scaling, physical units per voxel.</p></body></html>", None))
        self.line_edit_scaling_x.setText(_translate("Dialog", "1.0", None))
        self.label_boundaries.setToolTip(_translate("Dialog", "<html><head/><body><p>Edge length of whole dataset, only required if not starting from 2D images.</p></body></html>", None))
        self.label_boundaries.setText(_translate("Dialog", "Boundaries", None))
        self.line_edit_scaling_y.setToolTip(_translate("Dialog", "<html><head/><body><p>Voxel scaling, physical units per voxel.</p></body></html>", None))
        self.line_edit_scaling_y.setText(_translate("Dialog", "1.0", None))
        self.line_edit_boundaries_z.setToolTip(_translate("Dialog", "<html><head/><body><p>Edge length of whole dataset, only required if not starting from 2D images.</p></body></html>", None))
        self.line_edit_boundaries_y.setToolTip(_translate("Dialog", "<html><head/><body><p>Edge length of whole dataset, only required if not starting from 2D images.</p></body></html>", None))
        self.label_scaling_y.setToolTip(_translate("Dialog", "<html><head/><body><p>Voxel scaling, physical units per voxel.</p></body></html>", None))
        self.label_scaling_y.setText(_translate("Dialog", "y", None))
        self.label_boundaries_y.setToolTip(_translate("Dialog", "<html><head/><body><p>Edge length of whole dataset, only required if not starting from 2D images.</p></body></html>", None))
        self.label_boundaries_y.setText(_translate("Dialog", "y", None))
        self.label_scaling.setToolTip(_translate("Dialog", "<html><head/><body><p>Voxel scaling, physical units per voxel.</p></body></html>", None))
        self.label_scaling.setText(_translate("Dialog", "Scaling", None))
        self.label_source_dimensions.setToolTip(_translate("Dialog", "<html><head/><body><p>Input image dimensions. Required for raw images, otherwise determined directly from input images.</p></body></html>", None))
        self.label_source_dimensions.setText(_translate("Dialog", "Source Dimensions", None))
        self.line_edit_source_dimensions_x.setToolTip(_translate("Dialog", "<html><head/><body><p>Input image dimensions. Required for raw images, otherwise determined directly from input images.</p></body></html>", None))
        self.label_source_dimensions_y.setToolTip(_translate("Dialog", "<html><head/><body><p>Input image dimensions. Required for raw images, otherwise determined directly from input images.</p></body></html>", None))
        self.label_source_dimensions_y.setText(_translate("Dialog", "y", None))
        self.line_edit_source_dimensions_y.setToolTip(_translate("Dialog", "<html><head/><body><p>Input image dimensions. Required for raw images, otherwise determined directly from input images.</p></body></html>", None))
        self.label_boundaries_x.setText(_translate("Dialog", "x", None))
        self.label_source_dimensions_x.setText(_translate("Dialog", "x", None))
        self.combo_box_source_datatype.setToolTip(_translate("Dialog", "<html><head/><body><p>Input image pixel data type, required only for raw.</p></body></html>", None))
        self.combo_box_source_datatype.setItemText(0, _translate("Dialog", "uint8", None))
        self.combo_box_source_datatype.setItemText(1, _translate("Dialog", "uint16", None))
        self.check_box_swap_axes.setToolTip(_translate("Dialog", "<html><head/><body><p>Whether to swap axes. If yes, performs costly xy axes swap; this swap takes currently about as long as reading in each image file.</p></body></html>", None))
        self.check_box_swap_axes.setText(_translate("Dialog", "Swap Axes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Dataset", None))
        self.label_downsampling_workers.setToolTip(_translate("Dialog", "<html><head/><body><p>Number of CPU cores to use for downsampling.</p></body></html>", None))
        self.label_downsampling_workers.setText(_translate("Dialog", "Downsampling workers", None))
        self.label_buffer_size_in_cubes.setToolTip(_translate("Dialog", "<html><head/><body><p>How many cubes will be used. Ideally, this number should be greater than the number of cubes in a single z-layer of cubes.</p></body></html>", None))
        self.label_buffer_size_in_cubes.setText(_translate("Dialog", "Buffer size in cubes", None))
        self.spin_box_downsampling_workers.setToolTip(_translate("Dialog", "<html><head/><body><p>Number of CPU cores to use for downsampling.</p></body></html>", None))
        self.spin_box_compression_workers.setToolTip(_translate("Dialog", "<html><head/><body><p>Numer of CPU cores to use for compression.</p></body></html>", None))
        self.label_cube_edge_length.setToolTip(_translate("Dialog", "<html><head/><body><p>Use more than CPU cores available; 20 is good if you\'re on a local RAID array, higher numbers might help if you read / write from NFS.</p></body></html>", None))
        self.label_cube_edge_length.setText(_translate("Dialog", "Cube edge length", None))
        self.spin_box_cube_edge_length.setToolTip(_translate("Dialog", "<html><head/><body><p>Use more than CPU cores available; 20 is good if you\'re on a local RAID array, higher numbers might help if you read / write from NFS.</p></body></html>", None))
        self.radio_button_start_from_mag1.setToolTip(_translate("Dialog", "<html><head/><body><p>If you already have full-resolution cubes, you can start from those cubes to generate downsampled and / or compressed cubes.</p></body></html>", None))
        self.radio_button_start_from_mag1.setText(_translate("Dialog", "Start from full resolution cubes", None))
        self.radio_button_start_from_2d_images.setToolTip(_translate("Dialog", "<html><head/><body><p>Whether to generate cubes from 2D images.</p></body></html>", None))
        self.radio_button_start_from_2d_images.setText(_translate("Dialog", "Start from 2D images", None))
        self.label_compression_workers.setToolTip(_translate("Dialog", "<html><head/><body><p>Numer of CPU cores to use for compression.</p></body></html>", None))
        self.label_compression_workers.setText(_translate("Dialog", "Compression workers", None))
        self.check_box_downsample.setToolTip(_translate("Dialog", "<html><head/><body><p>Create downsampled cubes for magnification pyramid.</p></body></html>", None))
        self.check_box_downsample.setText(_translate("Dialog", "Create downsampled cubes", None))
        self.check_box_skip_already_generated.setToolTip(_translate("Dialog", "<html><head/><body><p>Skip target cubes that already exist. Useful to continue a run that was aborted.</p></body></html>", None))
        self.check_box_skip_already_generated.setText(_translate("Dialog", "Skip already generated cubes", None))
        self.spin_box_buffer_size_in_cubes.setToolTip(_translate("Dialog", "<html><head/><body><p>How many cubes will be used. Ideally, this number should be greater than the number of cubes in a single z-layer of cubes.</p></body></html>", None))
        self.label_io_workers.setToolTip(_translate("Dialog", "<html><head/><body><p>Use more than CPU cores available; 20 is good if you\'re on a local RAID array, higher numbers might help if you read / write from NFS.</p></body></html>", None))
        self.label_io_workers.setText(_translate("Dialog", "IO Workers", None))
        self.spin_box_io_workers.setToolTip(_translate("Dialog", "<html><head/><body><p>Use more than CPU cores available; 20 is good if you\'re on a local RAID array, higher numbers might help if you read / write from NFS.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Processing", None))
        self.label_path_to_openjpeg.setToolTip(_translate("Dialog", "<html><head/><body><p>Path to JPEG2000 compression executable, only needed when using JPEG2000.</p></body></html>", None))
        self.label_path_to_openjpeg.setText(_translate("Dialog", "Path to OpenJPEG", None))
        self.line_edit_path_to_openjpeg.setToolTip(_translate("Dialog", "<html><head/><body><p>Path to JPEG2000 compression executable, only needed when using JPEG2000.</p></body></html>", None))
        self.push_button_path_to_openjpeg.setText(_translate("Dialog", "...", None))
        self.label_compression_quality.setToolTip(_translate("Dialog", "<html><head/><body><p>0-100 for jpg (100 is best), 1-10 for j2k (lowest is best).</p></body></html>", None))
        self.label_compression_quality.setText(_translate("Dialog", "Compression Quality", None))
        self.label_compression_algorithm.setToolTip(_translate("Dialog", "<html><head/><body><p>Which compression algorithm to use for cubes.</p></body></html>", None))
        self.label_compression_algorithm.setText(_translate("Dialog", "Compression Algorithm", None))
        self.label_gauss_filter.setToolTip(_translate("Dialog", "<html><head/><body><p>Gaussian filter before compression to reduce artefacts, this really helps a lot for noisy data. Do NOT use it for near-noise-free data (SNR larger than about 10).</p></body></html>", None))
        self.label_gauss_filter.setText(_translate("Dialog", "Gauss filter ", None))
        self.combo_box_compression_algorithm.setToolTip(_translate("Dialog", "<html><head/><body><p>Which compression algorithm to use for cubes.</p></body></html>", None))
        self.combo_box_compression_algorithm.setItemText(0, _translate("Dialog", "JPEG", None))
        self.combo_box_compression_algorithm.setItemText(1, _translate("Dialog", "JPEG2000", None))
        self.spin_box_compression_quality.setToolTip(_translate("Dialog", "<html><head/><body><p>0-100 for jpg (100 is best), 1-10 for j2k (lowest is best).</p></body></html>", None))
        self.spin_box_double_gauss_filter.setToolTip(_translate("Dialog", "<html><head/><body><p>Gaussian filter before compression to reduce artefacts, this really helps a lot for noisy data. Do NOT use it for near-noise-free data (SNR larger than about 10).</p></body></html>", None))
        self.check_box_compress.setToolTip(_translate("Dialog", "<html><head/><body><p>Create compressed cubes for efficient network streaming.</p></body></html>", None))
        self.check_box_compress.setText(_translate("Dialog", "Create compressed cubes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Compression", None))
        self.push_button_start_job.setToolTip(_translate("Dialog", "<html><head/><body><p>Start the cubing job. Depending on the size of the input data and the performance / number of compute cores on this machine, this operation may take a very long time.</p></body></html>", None))
        self.push_button_start_job.setText(_translate("Dialog", "Start job", None))

