#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH=${HERE}/glibc/usr/lib/:${HERE}/lib/:$LD_LIBRARY_PATH
cd ${HERE}
./knossos "$@" || (export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HERE}/lib/supplemental && ./knossos "$@")
